_ctp_training_index:
    path:     /
    defaults: { _controller: "CommercetoolsTrainingBundle:Catalog:index" }

_ctp_training_product:
    path:    /product/{id}
    defaults: { _controller: "CommercetoolsTrainingBundle:Catalog:detail" }

_ctp_training_cart:
    path: /cart
    defaults: { _controller: "CommercetoolsTrainingBundle:Cart:index" }

_ctp_training_add_lineItem:
    path: /cart/add
    defaults: { _controller: "CommercetoolsTrainingBundle:Cart:addLineItem" }

_ctp_training_change_lineItem:
    path: /cart/change
    defaults: { _controller: "CommercetoolsTrainingBundle:Cart:changeLineItem" }

_ctp_training_delete_lineItem:
    path: /cart/delete
    defaults: { _controller: "CommercetoolsTrainingBundle:Cart:deleteLineItem" }
_ctp_training_checkout_success:
    path: /checkout/succes
    defaults: { _controller: "CommercetoolsTrainingBundle:Checkout:success" }

training_login:
    path: /login
    defaults: { _controller: "CommercetoolsTrainingBundle:User:login" }
training_login_check:
    path: /login_check
    defaults: { _controller: "CommercetoolsTrainingBundle:User:login" }
training_logout:
    path: /logout
